version: "3.9"

services:
  # ai-service:
  #   build: ./ai-service
  #   ports:
  #     - "8001:8000"
  # auth-service:
  #   build: ./auth-service
  #   ports:
  #     - "8002:8000"
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"   # UI
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"